### ISSUE TITLE
[Bug]: Sapling Growth Server Crash

### ISSUE THREAD

**Issue by WenXin20** [Mrbysco/Dense-Trees#1]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

`v43.2.7`

### Minecraft version

`v1.19.2`

### Mod version

`v2.0.0`

### Java version

`17`

### Issue Description

Occasionally my server will crash, I assume this happens when a sapling grows. I'm not sure if its because of a modded or vanilla sapling though.

### Additional Information

https://gist.github.com/WenXin20/4aa8cf842a6927f80cbf0bc72ae9a01e

**Comment by Mrbysco** [comment]
A new version has been uploaded to CurseForge that should fix the issue. It should be available shortly

**Comment by WenXin20** [comment]
Thanks!
