### ISSUE TITLE
[Bug]: Dense Warped/Crimson Stems are missing all relevant vanilla block tags

### ISSUE THREAD

**Issue by MuteTiefling** [Mrbysco/Dense-Trees#2]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

43.2.13

### Minecraft version

1.19.2

### Mod version

 DenseTrees-1.19.2-2.0.1.jar

### Java version

17.0.4.0

### Issue Description

Crimson Stem's Minecraft tags
![image](https://github.com/Mrbysco/Dense-Trees/assets/9543430/9fd857e0-bdb3-4a20-9d67-31b09520b069)

Dense Crimson Stem's tags:
![image](https://github.com/Mrbysco/Dense-Trees/assets/9543430/b69e480e-475a-4014-8766-93085ddab058)

Dense Warped Stems are similarly missing all tags. 

### Additional Information

https://github.com/EnigmaticaModpacks/Enigmatica9/issues/379

**Comment by Mrbysco** [comment]
A new version will be up shortly that adds them to the missing vanilla tags

**Comment by Mrbysco** [comment]
https://curseforge.com/minecraft/mc-mods/dense-trees/files/4568694
