### ISSUE TITLE
[Bug]: Crash on modded server

### ISSUE THREAD

**Issue by benurecarmin** [Mrbysco/Dense-Trees#3]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

43.2.14

### Minecraft version

1.19.2

### Mod version

2.1.0

### Java version

Java 17 (can't say more, it's an hosted server)

### Issue Description

Hi,
A crash happened on my server, I can't exactly say the reason because I wasn't connected, but my friend was planting Orchard saplings from "Oh the biome You'll Go".

[crash-2023-07-13_15.36.48-server.txt](https://github.com/Mrbysco/Dense-Trees/files/12040892/crash-2023-07-13_15.36.48-server.txt)

### Additional Information

If you need anything more I'll try to answer as quick as I can
[modlist.txt](https://github.com/Mrbysco/Dense-Trees/files/12040965/modlist.txt)

**Comment by Mrbysco** [comment]
A new version should be available shortly that should fix the problem

**Comment by benurecarmin** [comment]
Thank you a lot
